# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owned',
            name='times_recommended',
        ),
        migrations.AddField(
            model_name='game',
            name='times_recommended',
            field=models.IntegerField(default=0),
        ),
    ]
