# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=None, editable=False)),
                ('modified_date', models.DateField(default=None, editable=False)),
                ('flagged', models.BooleanField(default=False)),
                ('app_id', models.IntegerField()),
                ('steam_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameslist.GameInstance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
