# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-27 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0002_steamdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamdata',
            name='current_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='steamdata',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='steamdata',
            name='app_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='steamdata',
            name='steam_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameslist.GameInstance'),
        ),
    ]
