# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0002_game_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='parent_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameslist.Game'),
        ),
    ]
