# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import gameslist.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0003_auto_20190927_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='steam_score',
            field=models.IntegerField(default=0, validators=[gameslist.models.only_positive_or_zero]),
        ),
    ]
