# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import gameslist.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0004_auto_20190210_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='priority',
            field=models.FloatField(default=0.0, validators=[gameslist.models.only_positive_or_zero]),
        ),
    ]
