# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gameslist.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0005_game_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=None, editable=False)),
                ('modified_date', models.DateField(default=None, editable=False)),
                ('text', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='note',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='note',
            name='date_last_modified',
        ),
        migrations.AddField(
            model_name='game',
            name='created_date',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='game',
            name='modified_date',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='game',
            name='times_passed_over',
            field=models.IntegerField(default=0, validators=[gameslist.models.only_positive_or_zero]),
        ),
        migrations.AddField(
            model_name='game',
            name='times_recommended',
            field=models.IntegerField(default=0, validators=[gameslist.models.only_positive_or_zero]),
        ),
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='note',
            name='modified_date',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='created_date',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='modified_date',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='alternatename',
            name='parent_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameslist.Game'),
        ),
    ]
