# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import gameslist.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0006_auto_20181121_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='substantial_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='purchase_date',
            field=models.DateField(default=b'2018-11-26', validators=[gameslist.models.no_future], verbose_name='date purchased'),
        ),
    ]
