# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0008_auto_20190225_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='full_time_to_beat',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_format',
        ),
        migrations.RemoveField(
            model_name='game',
            name='location',
        ),
        migrations.RemoveField(
            model_name='game',
            name='metacritic',
        ),
        migrations.RemoveField(
            model_name='game',
            name='notes_old',
        ),
        migrations.RemoveField(
            model_name='game',
            name='substantial_progress',
        ),
        migrations.RemoveField(
            model_name='game',
            name='system',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user_score',
        ),
        migrations.RemoveField(
            model_name='gameinstance',
            name='notes_old',
        ),
        migrations.AddField(
            model_name='gametoinstance',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
