# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0010_auto_20190302_1524'),
    ]

    operations = [
        migrations.RenameField('Note', 'parent_game', 'parent_entity'),
        migrations.RenameField('AlternateName', 'parent_game', 'parent_entity'),
        migrations.AddField(
            model_name='Note',
            name='parent_entity_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='AlternateName',
            name='parent_entity_type',
            field=models.IntegerField(default=1),
        ),
    ]
