# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0011_auto_20190310_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=None, editable=False)),
                ('modified_date', models.DateField(default=None, editable=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateField(default=None)),
                ('note', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('parent_entity', models.IntegerField(default=1)),
                ('parent_entity_type', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameToSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameslist.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=None, editable=False)),
                ('modified_date', models.DateField(default=None, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('linear', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=None, editable=False)),
                ('modified_date', models.DateField(default=None, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('linear', models.BooleanField(default=False)),
                ('parent_series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameslist.Series')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='alternatename',
            name='parent_entity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent_entity',
            field=models.IntegerField(default=1),
        ),
    ]
