# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0012_auto_20190310_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametoseries',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameslist.Series'),
        ),
        migrations.AddField(
            model_name='gametoseries',
            name='subseries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameslist.SubSeries'),
        ),
    ]
