# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-30 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import gameslist.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0014_auto_20190523_0901'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='game',
        #     name='reviewed',
        # ),
        # migrations.RemoveField(
        #     model_name='gameinstance',
        #     name='perler',
        # ),
        # migrations.RemoveField(
        #     model_name='gameinstance',
        #     name='reviewed',
        # ),
        # migrations.RemoveField(
        #     model_name='gameinstance',
        #     name='substantial_progress',
        # ),
        # migrations.AddField(
        #     model_name='alternatename',
        #     name='flagged',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='flag',
        #     name='flagged',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='game',
        #     name='aging',
        #     field=models.IntegerField(default=0, validators=[gameslist.models.only_positive_or_zero]),
        # ),
        # migrations.AddField(
        #     model_name='game',
        #     name='play_aging',
        #     field=models.IntegerField(default=0, validators=[gameslist.models.only_positive_or_zero]),
        # ),
        migrations.AddField(
            model_name='game',
            name='substantial_progress',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='gameinstance',
        #     name='active',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='note',
        #     name='flagged',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='series',
        #     name='flagged',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='subseries',
        #     name='flagged',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='wish',
        #     name='flagged',
        #     field=models.BooleanField(default=False),
        # ),
    ]
