# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0015_auto_20190630_1414'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='game',
        #     name='reviewed',
        # ),
        # migrations.RemoveField(
        #     model_name='gameinstance',
        #     name='perler',
        # ),
        # migrations.RemoveField(
        #     model_name='gameinstance',
        #     name='reviewed',
        # ),
        # migrations.RemoveField(
        #     model_name='gameinstance',
        #     name='substantial_progress',
        # ),
        migrations.AddField(
            model_name='game',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('O', 'Owned'), ('B', 'Borrowed'), ('N', 'None')], default='O', max_length=3),
        ),
    ]
