# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import gameslist.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0016_auto_20190710_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='gameinstance',
            name='perler',
        ),
        migrations.RemoveField(
            model_name='gameinstance',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='gameinstance',
            name='substantial_progress',
        ),
        migrations.AddField(
            model_name='alternatename',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flag',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='game',
        #     name='aging',
        #     field=models.IntegerField(default=0, validators=[gameslist.models.only_positive_or_zero]),
        # ),
        # migrations.AddField(
        #     model_name='game',
        #     name='play_aging',
        #     field=models.IntegerField(default=0, validators=[gameslist.models.only_positive_or_zero]),
        # ),
        migrations.AddField(
            model_name='gameinstance',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subseries',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
