# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0017_auto_20190710_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametoseries',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gametoseries',
            name='series',
        ),
        migrations.RemoveField(
            model_name='gametoseries',
            name='subseries',
        ),
        migrations.RemoveField(
            model_name='subseries',
            name='parent_series',
        ),
        migrations.DeleteModel(
            name='GameToSeries',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='SubSeries',
        ),
    ]
