# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 00:10
from __future__ import unicode_literals

from django.db import migrations
from django.db import models
from gameslist.models import STATUSES

class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0018_auto_20190718_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(max_length=3, choices=STATUSES, default="O"),
        ),
    ]
