# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('system', models.CharField(choices=[('3DS', 'Nintendo 3DS'), ('AND', 'Android'), ('ATA', 'Atari'), ('DIG', 'Digipen'), ('NDS', 'Nintendo DS'), ('GCN', 'Gamecube'), ('GB', 'Game Boy'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('GG', 'GameGear'), ('GOG', 'GoG'), ('HUM', 'Humble'), ('IND', 'IndieBox'), ('IIO', 'Itch.io'), ('KIN', 'Kindle'), ('NES', 'Nintendo Entertainment System'), ('N64', 'Nintendo 64'), ('ORN', 'Origin'), ('PC', 'PC'), ('PSX', 'Playstation'), ('PS2', 'Playstation 2'), ('PS3', 'Playstation 3'), ('PS4', 'Playstation 4'), ('SNS', 'Super Nintendo Entertainment System'), ('STM', 'Steam'), ('NSW', 'Switch'), ('TWH', 'Twitch'), ('UPL', 'Uplay'), ('VIT', 'Vita'), ('WII', 'Wii'), ('WIU', 'Wii U'), ('XBX', 'Xbox'), ('360', 'Xbox 360'), ('XB1', 'Xbox One')], default='STM', max_length=3)),
                ('played', models.BooleanField(default=False)),
                ('beaten', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('3DS', 'Nintendo 3DS'), ('AND', 'Android'), ('ATA', 'Atari'), ('DIG', 'Digipen'), ('NDS', 'Nintendo DS'), ('GCN', 'Gamecube'), ('GB', 'Game Boy'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('GG', 'GameGear'), ('GOG', 'GoG'), ('HUM', 'Humble'), ('IND', 'IndieBox'), ('IIO', 'Itch.io'), ('KIN', 'Kindle'), ('NES', 'Nintendo Entertainment System'), ('N64', 'Nintendo 64'), ('ORN', 'Origin'), ('PC', 'PC'), ('PSX', 'Playstation'), ('PS2', 'Playstation 2'), ('PS3', 'Playstation 3'), ('PS4', 'Playstation 4'), ('SNS', 'Super Nintendo Entertainment System'), ('STM', 'Steam'), ('NSW', 'Switch'), ('TWH', 'Twitch'), ('UPL', 'Uplay'), ('VIT', 'Vita'), ('WII', 'Wii'), ('WIU', 'Wii U'), ('XBX', 'Xbox'), ('360', 'Xbox 360'), ('XB1', 'Xbox One')], default='STM', max_length=3)),
                ('game_format', models.CharField(choices=[('P', 'Physical'), ('D', 'Digital'), ('M', 'Missing'), ('B', 'Borrowed'), ('N', 'None'), ('R', 'Returned'), ('L', 'Lent'), ('E', 'Expired')], default='D', max_length=1, verbose_name='format')),
                ('notes', models.CharField(default='', max_length=500)),
                ('purchase_date', models.DateField(default=datetime.date.today, verbose_name='date purchased')),
                ('finish_date', models.DateField(default=datetime.date.today, verbose_name='date finished')),
                ('abandoned', models.BooleanField(default=False)),
                ('perler', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('aging', models.IntegerField(default=0)),
                ('play_aging', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('system', models.CharField(choices=[('3DS', 'Nintendo 3DS'), ('AND', 'Android'), ('ATA', 'Atari'), ('DIG', 'Digipen'), ('NDS', 'Nintendo DS'), ('GCN', 'Gamecube'), ('GB', 'Game Boy'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('GG', 'GameGear'), ('GOG', 'GoG'), ('HUM', 'Humble'), ('IND', 'IndieBox'), ('IIO', 'Itch.io'), ('KIN', 'Kindle'), ('NES', 'Nintendo Entertainment System'), ('N64', 'Nintendo 64'), ('ORN', 'Origin'), ('PC', 'PC'), ('PSX', 'Playstation'), ('PS2', 'Playstation 2'), ('PS3', 'Playstation 3'), ('PS4', 'Playstation 4'), ('SNS', 'Super Nintendo Entertainment System'), ('STM', 'Steam'), ('NSW', 'Switch'), ('TWH', 'Twitch'), ('UPL', 'Uplay'), ('VIT', 'Vita'), ('WII', 'Wii'), ('WIU', 'Wii U'), ('XBX', 'Xbox'), ('360', 'Xbox 360'), ('XB1', 'Xbox One')], default='STM', max_length=3)),
                ('played', models.BooleanField(default=False)),
                ('beaten', models.BooleanField(default=False)),
                ('date_added', models.DateField(default=datetime.date.today, verbose_name='date added')),
                ('below_latte', models.BooleanField(default=False)),
            ],
        ),
    ]
