# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0002_auto_20181030_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='aging',
        ),
        migrations.RemoveField(
            model_name='game',
            name='play_aging',
        ),
        migrations.AddField(
            model_name='game',
            name='full_time_to_beat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='finish_date',
            field=models.DateField(blank=True, default=None, verbose_name='date finished'),
        ),
        migrations.AlterField(
            model_name='game',
            name='purchase_date',
            field=models.DateField(default=b'2018-11-14', verbose_name='date purchased'),
        ),
    ]
