# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import gameslist.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0005_auto_20181117_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_time',
            field=models.FloatField(default=0.0, validators=[gameslist.models.only_positive_or_zero]),
        ),
        migrations.AlterField(
            model_name='game',
            name='full_time_to_beat',
            field=models.FloatField(default=0.0, validators=[gameslist.models.only_positive_or_zero]),
        ),
        migrations.AlterField(
            model_name='game',
            name='purchase_date',
            field=models.DateField(default=b'2018-11-21', validators=[gameslist.models.no_future], verbose_name='date purchased'),
        ),
    ]
