# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import gameslist.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0007_auto_20181126_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='purchase_date',
            field=models.DateField(default=None, validators=[gameslist.models.no_future], verbose_name='date purchased'),
        ),
    ]
