# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameslist', '0009_auto_20190116_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='notes_id',
        ),
        migrations.AddField(
            model_name='game',
            name='notes_old',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
